<?php

$title = 'Delete rule';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete rule
    '<?php echo $this->escapeHtml($rule->rule); ?>' with
    '<?php echo $this->escapeHtml($rule->points); ?>' points?
</p>
<?php
$url = $this->url('admin', array(
    'action' => 'delete',
    'controller' => 'rules',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $rule->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>
