<?php

$title = 'The rules';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><a href="<?php echo $this->url('admin', array('controller' => 'rules', 'action'=>'add'));?>">Add new rule</a></p>

<table class="table">
<tr>
    <th>Rule</th>
    <th>Points</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($rules as $rule) : ?>
<tr>
    <td><?php echo $this->escapeHtml($rule->rule);?></td>
    <td><?php echo $this->escapeHtml($rule->points);?></td>    <td>
        <a href="<?php echo $this->url('admin', array('controller' => 'rules', 'action'=>'edit', 'id' => $rule->id));?>">Edit</a>
        <a href="<?php echo $this->url('admin', array('controller' => 'rules', 'action'=>'delete', 'id' => $rule->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
